name: cloudapp run and deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout pannu 
        uses: actions/checkout@v4
      - name: code irukutha
        run : ls
      - name: node irukkiya
        run : node --version
      - name: package install panna porom
        run : npm install
      # - name: Build panna porom
      #   run : npm start
      - name: deploy panna porom
        run :  echo "Deploying the application..."
      - name: docker image build panna porom
        run: docker build -t dineshk1234/cloudtodo:latest .
      - name : docker login
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }}