name: cloudapp run and deploy
on:
  push:
    branches:
      - main

env:
  docker-image-name : dineshk1234/cloudtodo:latest
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout pannu 
        uses: actions/checkout@v4
      - name: code irukutha
        run : ls
      - name: node irukkiya
        run : node --version
      - name: package install panna porom
        run : npm install
      # - name: Build panna porom
      #   run : npm start
      - name: deploy panna porom
        run :  echo "Deploying the application..."
      - name: docker image build panna porom
        run: docker build -t ${{ env.docker-image-name }} .
      - name : docker login
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }}

      - name: docker image push panna porom
        run: docker push ${{ env.docker-image-name }} 
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: ssh name
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.HOSTIP }}
          username: my-ec2-instance
          key: ${{ secrets.AWSEC2KEY }}
          port: 22
          script: |
            echo "Deploying the application on the server..."
            docker pull ${{ env.docker-image-name }}
           
           